# Generated by Django 3.2.6 on 2021-08-27 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rawmaterials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_num', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('unit_size', models.PositiveIntegerField(blank=True, help_text='in milligrams', null=True)),
                ('label_claim', models.PositiveIntegerField(blank=True, help_text='in milligrams', null=True)),
                ('packaging', models.ImageField(blank=True, null=True, upload_to='products')),
                ('product_type', models.CharField(choices=[('CP', 'CAPLET'), ('TB', 'TABLET'), ('BL', 'BOLUS')], default='TB', max_length=20)),
                ('product_for', models.CharField(choices=[('HM', 'HUMAN'), ('VT', 'VET')], default='HM', max_length=20)),
                ('registration_number', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('equipments', models.ManyToManyField(blank=True, null=True, to='products.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.FloatField(blank=True)),
                ('deviation', models.FloatField(blank=True, null=True)),
                ('pharmacopiea', models.CharField(choices=[('USP', 'USP'), ('BP', 'BP')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.test')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_quantity', models.FloatField(blank=True, help_text='in kilograms or gram mil', null=True)),
                ('potency', models.FloatField(blank=True, help_text='in percentage', null=True)),
                ('percentage_formula', models.FloatField(blank=True, help_text='in percentage', null=True)),
                ('unit_formula_quantity', models.FloatField(blank=True, help_text='in milligrams', null=True)),
                ('batch_formula', models.FloatField(blank=True, help_text='in kilograms or gram mil', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawmaterials.rawmaterialbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('substep', models.CharField(max_length=2)),
                ('action', models.TextField(max_length=250)),
                ('duration', models.DurationField(blank=True, help_text='in minutes or seconds', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
