# Generated by Django 3.2.6 on 2021-11-06 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_manufacturingprocess_substep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturingprocess',
            name='substep',
        ),
        migrations.AddField(
            model_name='manufacturingprocess',
            name='serial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingprocess',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='manufacturingprocess',
            name='step',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
