# Generated by Django 3.2.6 on 2021-11-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_manufacturingprocess_order_with_respect_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturingprocess',
            name='serial',
        ),
        migrations.AlterField(
            model_name='manufacturingprocess',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
