# Generated by Django 3.2.6 on 2021-11-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211109_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingprocess',
            name='action_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingprocess',
            name='duration',
            field=models.CharField(blank=True, help_text='hours:minutes:seconds', max_length=100, null=True),
        ),
    ]
