# Generated by Django 3.2.6 on 2021-11-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20211110_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingprocess',
            name='step',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
