# Generated by Django 3.2.6 on 2021-08-27 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('rawmaterials', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=20)),
                ('gross_weight', models.FloatField(blank=True, help_text='in kilograms', null=True)),
                ('net_weight', models.FloatField(blank=True, help_text='in kilograms', null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_size', models.IntegerField(blank=True, null=True)),
                ('percentage_yield', models.IntegerField(blank=True, help_text='in percentage', null=True)),
                ('expected_yield', models.IntegerField(blank=True, help_text='in percentage', null=True)),
                ('actual_yield', models.FloatField(blank=True, null=True)),
                ('pack_size', models.IntegerField(blank=True, null=True)),
                ('production_commencement', models.DateField(blank=True, null=True)),
                ('production_completion', models.DateField(blank=True, null=True)),
                ('release_status', models.BooleanField(blank=True, default=False, null=True)),
                ('yield_deviation_limit', models.FloatField(blank=True, help_text='+/-', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(blank=True, null=True)),
                ('id_complies', models.NullBooleanField()),
                ('result_type', models.CharField(choices=[('CHM', 'CHEMICAL'), ('MCR', 'MICRO')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.test')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialPackagingBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispensed', models.IntegerField(blank=True, help_text='in kilograms', null=True)),
                ('dispensed_to', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawmaterialpackagingbill_action_by', to='staff.staff')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawmaterialpackagingbill_checked_by', to='staff.staff')),
                ('dispense_label_auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawmaterialpackagingbill_auth_by', to='staff.staff')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawmaterials.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialCheckRecordAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawmaterialcheckrecordauth_assignment', to='staff.staff')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('check_done_by', models.ManyToManyField(blank=True, null=True, to='staff.Staff')),
                ('total_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawmaterialcheckrecordauth_total_assignment', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialCheckRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tested', models.DateField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawmaterialcheckrecord_checked_by', to='staff.staff')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawmaterials.rawmaterialbatch')),
                ('weighed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawmaterialcheckrecord_weighed_by', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialBillAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawmaterialbillauth_approved_by', to='staff.staff')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('confirmed_by', models.ManyToManyField(blank=True, to='staff.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='QualityControlAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_number', models.CharField(max_length=50)),
                ('pharmacopiea_specification_year', models.DateField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('chemical_analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualitycontrolanalysis_chemical_analyst', to='staff.staff')),
                ('microbiologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualitycontrolanalysis_microbiologist', to='staff.staff')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('quality_control_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualitycontrolanalysis_QC_manager', to='staff.staff')),
                ('result_pharmacopiea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.specification')),
                ('results', models.ManyToManyField(blank=True, null=True, to='batches.TestResult')),
            ],
        ),
        migrations.CreateModel(
            name='InprocessAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('action_by', models.ManyToManyField(blank=True, null=True, related_name='inprocessauth_action_by', to='staff.Staff')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('checked_by', models.ManyToManyField(blank=True, null=True, related_name='inprocessauth_checked_by', to='staff.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualWieght',
            fields=[
                ('position', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
            ],
        ),
        migrations.CreateModel(
            name='ControlRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=50)),
                ('result', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_description', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleaningprocess_action_by', to='staff.staff')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleaningprocess_checked_by', to='staff.staff')),
            ],
        ),
    ]
