# Generated by Django 3.2.6 on 2021-11-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='records',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
