# Generated by Django 3.2.6 on 2021-11-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_batch_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='records',
        ),
    ]
