# Generated by Django 3.2.6 on 2021-11-17 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0005_auto_20211116_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchinfoauth',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='batchinfoauth',
            name='prepared_date',
        ),
        migrations.RemoveField(
            model_name='batchinfoauth',
            name='reviewed_date',
        ),
        migrations.AddField(
            model_name='batchinfoauth',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 17, 9, 43, 51, 538057, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchinfoauth',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
