# Generated by Django 3.2.6 on 2021-11-17 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0006_auto_20211117_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchinfoauth',
            name='batch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batchinfoauth_info_auth', to='batches.batch'),
        ),
    ]
