# Generated by Django 3.2.6 on 2021-11-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0007_alter_batchinfoauth_batch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guide',
        ),
    ]
