# Generated by Django 3.2.6 on 2021-11-21 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0008_delete_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_instructions', models.TextField(blank=True, max_length=8000, null=True)),
                ('issuance', models.TextField(blank=True, max_length=8000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
            ],
        ),
    ]
