# Generated by Django 3.2.6 on 2021-11-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('products', '0011_alter_manufacturingprocess_step'),
        ('batches', '0009_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentclearance',
            name='last_product',
        ),
        migrations.RemoveField(
            model_name='equipmentclearance',
            name='next_product',
        ),
        migrations.RemoveField(
            model_name='equipmentclearance',
            name='quality_assurance_manager',
        ),
        migrations.CreateModel(
            name='EQClearanceAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.equipmentclearance')),
                ('last_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eqclearanceauth_last_product', to='products.product')),
                ('next_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eqclearanceauth_next_product', to='products.product')),
                ('quality_assurance_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eqclearanceauth_qa_manager', to='staff.staff')),
            ],
        ),
    ]
