# Generated by Django 3.2.6 on 2021-11-24 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawmaterials', '0001_initial'),
        ('staff', '0001_initial'),
        ('batches', '0011_auto_20211124_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialbillauth',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawmaterialbillauth_action_by', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='rawmaterialbillauth',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawmaterialbillauth_checked_by', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='rawmaterialbillauth',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rawmaterials.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='rawmaterialbillauth',
            name='confirmed_by',
            field=models.ManyToManyField(blank=True, null=True, to='staff.Staff'),
        ),
    ]
