# Generated by Django 3.2.6 on 2021-11-24 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_manufacturingprocess_step'),
        ('batches', '0012_auto_20211124_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialbillauth',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='rawmaterialpackagingbill',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.rawmaterial'),
        ),
    ]
