# Generated by Django 3.2.6 on 2021-11-28 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0014_rawmaterialbillauth_actual_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialbillauth',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch'),
        ),
    ]
