# Generated by Django 3.2.6 on 2021-12-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0015_alter_rawmaterialbillauth_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchmanufacturingprocessauth',
            name='process',
        ),
        migrations.RemoveField(
            model_name='batchmanufacturingprocessauth',
            name='production_manager',
        ),
        migrations.DeleteModel(
            name='BatchManufacturingProcess',
        ),
        migrations.DeleteModel(
            name='BatchManufacturingProcessAuth',
        ),
    ]
