# Generated by Django 3.2.6 on 2021-12-12 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_rawmaterial_standard_quantity'),
        ('staff', '0001_initial'),
        ('batches', '0016_auto_20211212_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchManufacturingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_from', models.DateTimeField(blank=True, null=True)),
                ('action_to', models.DateTimeField(blank=True, null=True)),
                ('manufacturing_commenced', models.DateField()),
                ('manufacturing_completed', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batchmanufacturingprocess_action_by', to='staff.staff')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batchmanufacturingprocess_checked_by', to='staff.staff')),
                ('production_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batchmanufacturingprocess_production_manager', to='staff.staff')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.manufacturingprocess')),
            ],
        ),
    ]
