# Generated by Django 3.2.6 on 2021-12-19 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('batches', '0019_auto_20211212_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialcheckrecord',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawmaterialcheckrecord_assignment', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='rawmaterialcheckrecord',
            name='check_done_by',
            field=models.ManyToManyField(blank=True, null=True, to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='rawmaterialcheckrecord',
            name='total_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawmaterialcheckrecord_total_assignment', to='staff.staff'),
        ),
        migrations.DeleteModel(
            name='RawMaterialCheckRecordAuth',
        ),
    ]
