# Generated by Django 3.2.6 on 2021-12-26 12:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('batches', '0020_auto_20211219_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ManyToManyField(blank=True, null=True, related_name='individualweight_approved_by', to='staff.Staff')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('checked_by', models.ManyToManyField(blank=True, null=True, related_name='individualweight_checked_by', to='staff.Staff')),
            ],
        ),
        migrations.RemoveField(
            model_name='inprocessauth',
            name='action_by',
        ),
        migrations.RemoveField(
            model_name='inprocessauth',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='inprocessauth',
            name='checked_by',
        ),
        migrations.AddField(
            model_name='cleaningprocess',
            name='approved_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='cleaningprocess_approved_by', to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='controlrecords',
            name='approved_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='controlrecords_approved_by', to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='controlrecords',
            name='checked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='controlrecords_checked_by', to='staff.Staff'),
        ),
        migrations.RemoveField(
            model_name='cleaningprocess',
            name='checked_by',
        ),
        migrations.AddField(
            model_name='cleaningprocess',
            name='checked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='cleaningprocess_auth_checked_by', to='staff.Staff'),
        ),
        migrations.DeleteModel(
            name='IndividualWieght',
        ),
        migrations.DeleteModel(
            name='InprocessAuth',
        ),
    ]
