# Generated by Django 3.2.6 on 2021-12-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_rawmaterial_standard_quantity'),
        ('batches', '0021_auto_20211226_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlrecords',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controlrecords_spec', to='products.specification'),
        ),
    ]
