# Generated by Django 3.2.6 on 2022-01-08 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('batches', '0022_alter_controlrecords_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningprocess',
            name='process_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleaningprocess_checked_by', to='staff.staff'),
        ),
    ]
