# Generated by Django 3.2.6 on 2022-01-29 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_rawmaterial_standard_quantity'),
        ('batches', '0023_cleaningprocess_process_checked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitycontrolanalysis',
            name='results',
        ),
        migrations.AddField(
            model_name='qualitycontrolanalysis',
            name='result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qualitycontrolanalysis',
            name='result_type',
            field=models.CharField(blank=True, choices=[('CHM', 'CHEMICAL'), ('MCR', 'MICRO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qualitycontrolanalysis',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.test'),
        ),
        migrations.AlterField(
            model_name='qualitycontrolanalysis',
            name='ar_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
