# Generated by Django 3.2.6 on 2022-02-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0024_auto_20220129_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycontrolanalysis',
            name='result_specification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qualitycontrolanalysis',
            name='result_pharmacopiea',
            field=models.CharField(blank=True, choices=[('BP', 'BP'), ('USP', 'USP')], max_length=10, null=True),
        ),
    ]
