# Generated by Django 3.2.6 on 2022-03-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0025_auto_20220225_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycontrolanalysis',
            name='pharmacopiea_specification_year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
