# Generated by Django 3.2.6 on 2022-03-05 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0026_alter_qualitycontrolanalysis_pharmacopiea_specification_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchpackagingauth',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch', unique=True),
        ),
    ]
