# Generated by Django 3.2.6 on 2022-03-18 20:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('batches', '0027_alter_batchpackagingauth_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuantitySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_quantity', models.CharField(max_length=100)),
                ('remarks', models.TextField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReconPackMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_supplied', models.IntegerField(blank=True, null=True)),
                ('quantity_damaged', models.IntegerField(blank=True, null=True)),
                ('quantity_rejected', models.IntegerField(blank=True, null=True)),
                ('quantity_returned', models.IntegerField(blank=True, null=True)),
                ('quantity_used', models.IntegerField(blank=True, null=True)),
                ('percentage_breakage', models.FloatField(blank=True, help_text='in percentage', null=True)),
                ('percentage_damages', models.FloatField(blank=True, help_text='in percentage', null=True)),
                ('deviation', models.FloatField(blank=True, help_text='+/- (%)', null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.packagingmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(max_length=100)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productsamples_approved_by', to='staff.staff')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productsamples_issued_by', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ProductYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_percent_yield', models.IntegerField(blank=True, null=True)),
                ('expected_yield_deviation', models.IntegerField(blank=True, null=True)),
                ('expected_yield_dev_limit', models.IntegerField(blank=True, null=True)),
                ('expected_yield_pack_sizes', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('actual_percent_yield', models.IntegerField(blank=True, null=True)),
                ('actual_yield_deviation', models.IntegerField(blank=True, null=True)),
                ('actual_yield_dev_limit', models.IntegerField(blank=True, null=True)),
                ('actual_yield_pack_sizes', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
            ],
        ),
        migrations.AddField(
            model_name='releaseprofile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batches.batch'),
        ),
        migrations.DeleteModel(
            name='ProductReconciliation',
        ),
    ]
